package com.ismayfly.coins.tools.mapper;

import com.ismayfly.coins.tools.model.po.McShopCodeMapping;
import java.util.List;

public interface McShopCodeMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shop_code_mapping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shop_code_mapping
     *
     * @mbggenerated
     */
    int insert(McShopCodeMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shop_code_mapping
     *
     * @mbggenerated
     */
    McShopCodeMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shop_code_mapping
     *
     * @mbggenerated
     */
    List<McShopCodeMapping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shop_code_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(McShopCodeMapping record);
}