package com.ismayfly.coins.tools.mapper;

import com.ismayfly.coins.tools.model.po.McShopcodeMapping;

import java.util.List;

public interface McShopcodeMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shopcode_mapping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shopcode_mapping
     *
     * @mbggenerated
     */
    int insert(McShopcodeMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shopcode_mapping
     *
     * @mbggenerated
     */
    McShopcodeMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shopcode_mapping
     *
     * @mbggenerated
     */
    List<McShopcodeMapping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shopcode_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(McShopcodeMapping record);
}