package com.ismayfly.coins.tools.mapper;

import com.ismayfly.coins.tools.model.po.MdSocialInformation;
import java.util.List;

public interface MdSocialInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_social_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_social_information
     *
     * @mbggenerated
     */
    int insert(MdSocialInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_social_information
     *
     * @mbggenerated
     */
    MdSocialInformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_social_information
     *
     * @mbggenerated
     */
    List<MdSocialInformation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_social_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MdSocialInformation record);
}