package com.ismayfly.coins.tools.mapper;

import com.ismayfly.coins.tools.model.po.MpPayConfigBank;
import java.util.List;

public interface MpPayConfigBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_pay_config_bank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_pay_config_bank
     *
     * @mbggenerated
     */
    int insert(MpPayConfigBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_pay_config_bank
     *
     * @mbggenerated
     */
    MpPayConfigBank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_pay_config_bank
     *
     * @mbggenerated
     */
    List<MpPayConfigBank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_pay_config_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MpPayConfigBank record);
}