package com.ismayfly.coins.tools.model.po;

import java.io.Serializable;

public class MdSocialInformation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.qq
     *
     * @mbggenerated
     */
    private Long qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.wb_uid
     *
     * @mbggenerated
     */
    private Long wbUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.wb_url
     *
     * @mbggenerated
     */
    private String wbUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_social_information.third_id
     *
     * @mbggenerated
     */
    private Long thirdId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.id
     *
     * @return the value of md_social_information.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.id
     *
     * @param id the value for md_social_information.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.user_name
     *
     * @return the value of md_social_information.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.user_name
     *
     * @param userName the value for md_social_information.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.nick_name
     *
     * @return the value of md_social_information.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.nick_name
     *
     * @param nickName the value for md_social_information.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.mobile
     *
     * @return the value of md_social_information.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.mobile
     *
     * @param mobile the value for md_social_information.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.qq
     *
     * @return the value of md_social_information.qq
     *
     * @mbggenerated
     */
    public Long getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.qq
     *
     * @param qq the value for md_social_information.qq
     *
     * @mbggenerated
     */
    public void setQq(Long qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.wb_uid
     *
     * @return the value of md_social_information.wb_uid
     *
     * @mbggenerated
     */
    public Long getWbUid() {
        return wbUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.wb_uid
     *
     * @param wbUid the value for md_social_information.wb_uid
     *
     * @mbggenerated
     */
    public void setWbUid(Long wbUid) {
        this.wbUid = wbUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.wb_url
     *
     * @return the value of md_social_information.wb_url
     *
     * @mbggenerated
     */
    public String getWbUrl() {
        return wbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.wb_url
     *
     * @param wbUrl the value for md_social_information.wb_url
     *
     * @mbggenerated
     */
    public void setWbUrl(String wbUrl) {
        this.wbUrl = wbUrl == null ? null : wbUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.group_id
     *
     * @return the value of md_social_information.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.group_id
     *
     * @param groupId the value for md_social_information.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_social_information.third_id
     *
     * @return the value of md_social_information.third_id
     *
     * @mbggenerated
     */
    public Long getThirdId() {
        return thirdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_social_information.third_id
     *
     * @param thirdId the value for md_social_information.third_id
     *
     * @mbggenerated
     */
    public void setThirdId(Long thirdId) {
        this.thirdId = thirdId;
    }

    public MdSocialInformation(){

    }


}